### PR TITLE
Worker id must include a queue

### PR DESCRIPTION
**Pull request by zerowidth**
So the workers using this branch don't confuse (read: break) resque workers that are sharing the same infrastructure but not this code, and which are expecting a three-part worker id.

We have a small number of resque workers sharing our resque redis infrastructure, but which are running "vanilla" resque rather than this customized branch. However, the shortened/simplified worker ids introduced in #10 break regular redis workers which are expecting a three-part `hostname:pid:list,of,queues` identifier rather than `hostname:pid`.

This branch fixes it by adding back an empty third part of a worker id, that is: `hostname:pid:-` -- which is interpreted as a single queue `["-"]`. It's not empty because `Worker.find` will raise if the list of queues is entirely empty, so a minimal and clearly not-normally-valid queue name of `-` is a part of the id.

Here's the error:

```
irb> Resque::Worker.all
NoMethodError: undefined method `split' for nil:NilClass
	from /path/to/app/vendor/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/worker.rb:93:in `find'
	from /path/to/app/vendor/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/worker.rb:56:in `block in all'
	from /path/to/app/vendor/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/worker.rb:56:in `map'
	from /path/to/app/vendor/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/worker.rb:56:in `all'
	from (irb):3
	from /usr/share/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.3.0/lib/bundler/cli.rb:611:in `console'
	from /usr/share/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.3.0/lib/bundler/vendor/thor/task.rb:27:in `run'
	from /usr/share/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.3.0/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'
	from /usr/share/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.3.0/lib/bundler/vendor/thor.rb:344:in `dispatch'
	from /usr/share/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.3.0/lib/bundler/vendor/thor/base.rb:434:in `start'
	from /usr/share/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.3.0/bin/bundle:20:in `block in <top (required)>'
	from /usr/share/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.3.0/lib/bundler/friendly_errors.rb:4:in `with_friendly_errors'
	from /usr/share/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.3.0/bin/bundle:20:in `<top (required)>'
	from /usr/share/rbenv/versions/2.2.3/bin/bundle:23:in `load'
	from /usr/share/rbenv/versions/2.2.3/bin/bundle:23:in `<main>'
```

cc @github/high-availability @github/background-jobs

### CODE REVIEW

**Comment by jnunemaker** [comment]
> So the workers using this branch don't confuse (read: break) resque workers that are sharing the same infrastructure but not this code, and which are expecting a three-part worker id.
>
> We have a small number of resque workers sharing our resque redis infrastructure, but which are running "vanilla" resque rather than this customized branch.

Would you mind explaining this a bit more or linking to relevant issues? What does sharing our resque redis infrastructure mean? Are they pointed at the same redis instance and operating on the same queues, but with different resque versions?

**Comment by zerowidth** [comment]
> Are they pointed at the same redis instance and operating on the same queues, but with different resque versions?

Yep, that's exactly it. We have most resque workers using this GitHub-specific fork of resque -- now with the simplified worker ids `hostname:pid`. A small handful of resque workers are sharing the redis server and resque infrastructure (that is, redis keys like `resque:queues`, etc), and because the worker id is different it breaks the resque code with the backtrace I pasted above: mainline resque expects the queue list in the worker ids, and breaks if it's not there. By adding back a `-` fake queue, it'll make mainline resque workers happy while preserving the small-key benefits from #10 for the majority of our workers.

**Comment by zerowidth** [comment]
This worked just fine, and both mainline resque and our fork play nicely together now.
